name: Test

on:
  workflow_dispatch:
    
jobs:
  dostuff:
    name: Lol
    runs-on: ubuntu-latest
    steps:
      - name: Sanity check
        id: sanity
        run: |
          echo "LOL"
          echo "OMG" > omg
      - name: Check 2
        run: |
          echo "${{ steps.sanity.outputs.stdout }}"